import Head from "next/head";

import { BoardLayout } from "@/page-implementations/boards/layouts/board.layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BoardLayout>Hello world</BoardLayout>
    </>
  );
}
