import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

import { LoadingPage } from "@/components/common/loading-page";
import { Routes } from "@/config/routes";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    void router.push(Routes.teams.home);
  }, [router]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoadingPage message="Loading teams" />
    </>
  );
}
